### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by bruce-forte** [agorahq/agora#15]
This **epic** is about managing *User*s. It consists of the following

### Features:

- [x] #2 Register to Agora as a User
- [x] #3 Log in to Agora as a User or Admin
- [x] #14 Permission System for Agora
- [ ] #26 Show profile
- [ ] #28 Subscribe to notifications for users
- [ ] #29 Delete own data
