### ISSUE TITLE
Post management

### ISSUE THREAD

**Issue by bruce-forte** [agorahq/agora#17]
### Features

- [x] #6 Create or edit posts
- [x] #5 Show post details
- [x] #4 List posts
- [ ] #10 Filtering for posts and events
- [ ] #34 Integrate CKEditor to enable WYSIWYG editing

### Depends on

- [x] #14 Permission system
