### ISSUE TITLE
Attendee management

### ISSUE THREAD

**Issue by bruce-forte** [agorahq/agora#27]
This **epic** is about managing *Attendee*s.

### Features

- [ ] #20 Show list of attendees
- [ ] #21 Show attendee details
- [ ] #22 Send email to attendee
- [ ] #23 Disable commenting for attendee
- [ ] #24 Disable RSVP for attendee
- [ ] #24 Ban Attendee
